import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'osher',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    
  ],
  products: [
    {
      // _id: '1',
      name: 'Nike Slim shirt',
      slug: 'nike-slim-shirt',
      category: 'Shirts',
      image: '/images/p1.jpg', // 679px × 829px
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 3.5,
      numReviews: 5,
      description: 'high quality shirt',
    },
    {
      // _id: '2',
      name: 'Adidas Fit Shirt',
      slug: 'adidas-fit-shirt',
      category: 'Shirts',
      image: '/images/p2.jpg',
      price: 250,
      countInStock: 0,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 7,
      description: 'high quality product',
    },
    {
      // _id: '3',
      name: 'Nike Slim Pant',
      slug: 'nike-slim-pant',
      category: 'Pants',
      image: '/images/p3.jpg',
      price: 25,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },
    {
      // _id: '4',
      name: 'Adidas Fit Pant',
      slug: 'adidas-fit-pant',
      category: 'Pants',
      image: '/images/p4.jpg',
      price: 65,
      countInStock: 5,
      brand: 'Puma',
      rating: 2.5,
      numReviews: 2,
      description: 'high quality product',
    },
    {
      // _id: '5',
      name: 'Nike Black shoes',
      slug: 'nike-black-shoes',
      category: 'shoes',
      image: '/images/p5.jpg',
      price: 200,
      countInStock: 10,
      brand: 'Nike',
      rating: 5.0,
      numReviews: 25,
      description: 'high quality product',
    },
    {
      // _id: '6',
      name: 'North Face Jacket',
      slug: 'north-face-jacket',
      category: 'Jackets',
      image: '/images/p6.jpg',
      price: 300,
      countInStock: 1,
      brand: 'North Face',
      rating: 1.5,
      numReviews: 5,
      description: 'high quality product',
    },
    {
      // _id: '7',
      name: 'Adidas T-shirt',
      slug: 'adidas-T shirt',
      category: 'Shirts',
      image: '/images/p7.jpg',
      price: 30,
      countInStock: 20,
      brand: 'Adidas',
      rating: 1.0,
      numReviews: 12,
      description: 'high quality product',
    },
    {
      // _id: '8',
      name: 'Nike Hat',
      slug: 'nike-hat',
      category: 'Hats',
      image: '/images/p9.jpg',
      price: 45,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
  ],
};
export default data;
